# Generated by Django 3.2 on 2022-04-12 08:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='news/%Y/%m/%d', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_oz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание')),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание')),
                ('description_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание')),
                ('short_description', models.CharField(max_length=500, verbose_name='Короткое описание')),
                ('short_description_ru', models.CharField(max_length=500, null=True, verbose_name='Короткое описание')),
                ('short_description_en', models.CharField(max_length=500, null=True, verbose_name='Короткое описание')),
                ('short_description_uz', models.CharField(max_length=500, null=True, verbose_name='Короткое описание')),
                ('short_description_oz', models.CharField(max_length=500, null=True, verbose_name='Короткое описание')),
                ('news_type', models.IntegerField(choices=[(1, 'uzbekistan'), (2, 'fond_yangiliklari'), (3, 'WORLD NEWS'), (4, 'savohat')], verbose_name='Тип')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
