# Generated by Django 3.2 on 2022-04-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saxovat_va_komak', '0003_alter_jamgarma_jamgarma_yili'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamgarma',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
