# Generated by Django 3.2 on 2022-03-26 19:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_for_display', models.ImageField(upload_to='region/%Y/%m/%d', verbose_name='Главная фото')),
                ('image_for_director', models.ImageField(upload_to='region/%Y/%m/%d', verbose_name='Фото директора')),
                ('subsection_name', models.CharField(max_length=255, verbose_name='Название регионалное отделение')),
                ('subsection_name_ru', models.CharField(max_length=255, null=True, verbose_name='Название регионалное отделение')),
                ('subsection_name_en', models.CharField(max_length=255, null=True, verbose_name='Название регионалное отделение')),
                ('subsection_name_uz', models.CharField(max_length=255, null=True, verbose_name='Название регионалное отделение')),
                ('subsection_name_oz', models.CharField(max_length=255, null=True, verbose_name='Название регионалное отделение')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('fio_ru', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('fio_en', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('fio_uz', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('fio_oz', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('visiting_time', models.CharField(max_length=255, verbose_name='Приём (10:00-18:80)')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('address_ru', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('address_uz', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('address_oz', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Биография')),
                ('bio_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Биография')),
                ('bio_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Биография')),
                ('bio_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Биография')),
                ('bio_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Биография')),
                ('goal', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Долж обязанности')),
                ('goal_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Долж обязанности')),
                ('goal_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Долж обязанности')),
                ('goal_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Долж обязанности')),
                ('goal_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Долж обязанности')),
            ],
            options={
                'verbose_name': 'администрация регионального отделения',
                'verbose_name_plural': 'Администрации региональных отделений',
            },
        ),
    ]
