# Generated by Django 3.2 on 2022-04-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20220408_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('toshkent_shahar', 'Toshkent sh'), ('andijon', 'Andijon v'), ('namangan', 'Namangan v'), ('fargona', "Farg'ona v"), ('toshkent_viloyati', 'Toshkent v'), ('sirdaryo', 'Sirdaryo v'), ('jizzax', 'Jizzax v'), ('samarqand', 'Samarqand v'), ('navoi', 'Navoi v'), ('qashqadaryo', 'Qashqadaryo v'), ('surxondaryo', 'Surxondaryo v'), ('buxoro', 'Buxoro v'), ('xorazm', 'Xorazm v'), ('qoraqalpogiston', "Qoraqalpog'iston R")], default=1, max_length=100, verbose_name='Выберите регион'),
            preserve_default=False,
        ),
    ]
