# Generated by Django 3.2 on 2022-03-26 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stir', models.CharField(max_length=255, verbose_name='ИНН')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('card_number_uzs', models.CharField(max_length=255, verbose_name='Номер карта uzs')),
                ('card_number_usd', models.CharField(max_length=255, verbose_name='Номер карта uzd')),
                ('card_number_eur', models.CharField(max_length=255, verbose_name='Номер карта eur')),
                ('district_name', models.CharField(max_length=255, verbose_name='Город')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Реквизит',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
    ]
