# Generated by Django 3.2 on 2022-03-26 19:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_oz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Краткое описание')),
                ('short_description_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Краткое описание')),
                ('short_description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Краткое описание')),
                ('short_description_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Краткое описание')),
                ('short_description_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Краткое описание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание')),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание')),
                ('description_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='ads/%Y/%m/%d', verbose_name='Рекламы')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
