# Generated by Django 3.2 on 2022-04-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО руководителя пресс-служба')),
                ('fio_ru', models.CharField(max_length=150, null=True, verbose_name='ФИО руководителя пресс-служба')),
                ('fio_en', models.CharField(max_length=150, null=True, verbose_name='ФИО руководителя пресс-служба')),
                ('fio_uz', models.CharField(max_length=150, null=True, verbose_name='ФИО руководителя пресс-служба')),
                ('fio_oz', models.CharField(max_length=150, null=True, verbose_name='ФИО руководителя пресс-служба')),
                ('image', models.ImageField(upload_to='press_contact/%Y/%m/%d', verbose_name='Фото руководителя')),
                ('position', models.CharField(max_length=150, verbose_name='Должность руководителя')),
                ('position_ru', models.CharField(max_length=150, null=True, verbose_name='Должность руководителя')),
                ('position_en', models.CharField(max_length=150, null=True, verbose_name='Должность руководителя')),
                ('position_uz', models.CharField(max_length=150, null=True, verbose_name='Должность руководителя')),
                ('position_oz', models.CharField(max_length=150, null=True, verbose_name='Должность руководителя')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, verbose_name='Телефоне')),
            ],
            options={
                'verbose_name': 'Пресс-контакт',
                'verbose_name_plural': 'Пресс-контакти',
            },
        ),
    ]
