# Generated by Django 3.2 on 2022-04-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_presscontact_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
