# Generated by Django 3.2 on 2022-03-26 19:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='adminstration/%Y/%m/%d', verbose_name='Фото')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('fio_ru', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('fio_en', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('fio_uz', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('fio_oz', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('position_ru', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('position_uz', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('position_oz', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('visiting_time', models.CharField(max_length=255, verbose_name='Приём (10:00-18:00)')),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Биография')),
                ('bio_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Биография')),
                ('bio_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Биография')),
                ('bio_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Биография')),
                ('bio_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Биография')),
                ('goal', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Долж обязанности')),
                ('goal_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Долж обязанности')),
                ('goal_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Долж обязанности')),
                ('goal_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Долж обязанности')),
                ('goal_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Долж обязанности')),
            ],
            options={
                'verbose_name': 'Руководство',
                'verbose_name_plural': 'Руководства',
            },
        ),
    ]
